Team1/Team1/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("signInUp.urls")),
    path("mainPage/", include("mainPage.urls")),
    path("detailPage/", include("detailPage.urls")),
    path("myPage/", include("myPage.urls")),
]

Team1/signInUp/urls.py
from django.urls import path
from . import views

app_name = "signInUp" #namespace 가 signInUp 라는 이름을 가졌음을 명시

urlpatterns = [
    path('signup/', views.signup, name='signup'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
]

Team1/signInUp/views.py
from django.contrib import messages
from django.contrib.auth import authenticate, login as auth_login, logout as auth_logout
from django.contrib.auth.models import User
from django.shortcuts import render, redirect
import re

from myPage.models import UserProfile

def signup(request):
    form_errors = {}
    missing_fields = []

    if request.method == 'POST':
        email = request.POST.get('email', '')
        password = request.POST.get('password', '')
        repeat_password = request.POST.get('repeat_password', '')
        nickname = request.POST.get('nickname', '')
        gender = request.POST.get('gender', '')
        birth_year = request.POST.get('birth_year', '')
        birth_month = request.POST.get('birth_month', '')
        birth_day = request.POST.get('birth_day', '')

        # 누락된 입력 체크
        if not email or not password or not repeat_password or not nickname or not gender or not birth_year or not birth_month or not birth_day:
            missing_fields.append('빠진 정보가 있는지 확인해주세요.')

        # 이메일 형식 검사
        email_regex = r'^[\w\.-]+@[\w\.-]+\.\w+$'
        if not re.match(email_regex, email):
            form_errors['email'] = '이메일 주소를 다시 확인해주세요.'
        elif User.objects.filter(email=email).exists():
            form_errors['email'] = '이미 사용 중인 이메일입니다.'

        # 비밀번호 일치 및 규칙 검사
        if password != repeat_password:
            form_errors['password'] = '비밀번호가 일치하지 않습니다.'
        elif len(password) < 8 or not re.search(r'[A-Za-z]', password) or not re.search(r'[0-9]', password) or not re.search(r'[\W_]', password):
            form_errors['password'] = '비밀번호는 문자/숫자/기호를 사용하여 8자리 이상이어야 합니다.'

        # 닉네임 길이 및 중복 검사
        if len(nickname) > 8:
            form_errors['nickname'] = '닉네임은 8자 이내여야 합니다.'
        elif User.objects.filter(first_name=nickname).exists():
            form_errors['nickname'] = '중복된 닉네임입니다.'

        # 모든 조건이 충족되면 회원 가입 진행
        if not form_errors and not missing_fields:
            new_user = User.objects.create_user(username=email, email=email, password=password, first_name=nickname)

            # UserProfile 생성
            UserProfile.objects.create(
                user=new_user,
                nickname=nickname,
                alert=False,
                using_credit=0,
                remaining_credit=0,
                credit_period='',
                phone_number=''
            )

            request.session['nickname'] = nickname

            # 회원가입 완료 페이지로 이동
            return render(request, 'signup_complete.html', {'nickname': nickname})

    return render(request, 'signup.html', {'form_errors': form_errors, 'missing_fields': missing_fields})

def login(request):
    if request.method == 'POST':
        username = request.POST.get('email', '')
        password = request.POST.get('password', '')

        user = authenticate(request, username=username, password=password)  # 'username'으로 변경
        if user is not None:
            auth_login(request, user)
            print('로그인 성공')
            return redirect('mainPage')  # 로그인 성공 후 mainPage로 이동
        else:
            error_message = "아이디 또는 비밀번호가 잘못되었습니다."
            return render(request, 'login.html', {'error_message': error_message})
    else:
        return render(request, 'login.html')

def logout(request):
    auth_logout(request)
    print('로그아웃 성공')
    return redirect('myPage')

Team1/signInUp/templates/login.html
{% block content %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>로그인</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/login.css' %}">
</head>
<body>
    {% load static %}
    <div class="login-container">
        <img src="{% static 'img/logo.png' %}" alt="CLASSFIT 로고" class="logo">
    
        <form method="POST" class="login-form">
            {% csrf_token %}
            <input type="text" name="email" placeholder="아이디를 입력하세요" required>
            <input type="password" name="password" placeholder="비밀번호를 입력하세요" required>

            <div class="login-options">
                <input type="radio" id="remember-me" name="remember" class="radio-btn">
                <label for="remember-me" class="radio-label">로그인 유지</label>
            </div>

            <button type="submit" class="login-button">로그인</button>

            {% if error_message %}
                <p style="color: red;">{{ error_message }}</p>
            {% endif %}
        </form>

        <div class="social-login">
            <img src="{% static 'img/naver.png' %}" alt="네이버 로그인" class="social-icon">
            <img src="{% static 'img/kakao.png' %}" alt="카카오 로그인" class="social-icon">
        </div>

        <div class ="extra-options">
            <a href="#">비밀번호 찾기</a> | 
            <a href="#">아이디 찾기</a> | 
            <a href="{% url 'signInUp:signup' %}">회원가입</a>
        </div>
    </div>
    <script src="{% static '/js/login.js' %}"></script>
</body>
</html>
{% endblock %}

Team1/signInUp/templates/signup.html
{% block content %}
<div class="wrapper" style="text-align: center;">
    <h1>회원가입</h1>
    <form method="POST">
        {% csrf_token %}
        이메일: <br>
        <input name="email" type="email" value="{{ request.POST.email }}">
        <br>
        {% if form_errors.email %}
            <p style="color: red;">{{ form_errors.email }}</p>
        {% endif %}
        비밀번호: <br>
        <input name="password" type="password" value="{{ request.POST.password }}">
        <br>
        {% if form_errors.password %}
            <p style="color: red;">{{ form_errors.password }}</p>
        {% endif %}
        비밀번호 확인: <br>
        <input name="repeat_password" type="password" value="{{ request.POST.repeat_password }}">
        <br>
        닉네임: <br>
        <input name="nickname" type="text" value="{{ request.POST.nickname }}">
        <br>
        {% if form_errors.nickname %}
            <p style="color: red;">{{ form_errors.nickname }}</p>
        {% endif %}
        성별: <br>
        <input type="radio" name="gender" value="male" {% if request.POST.gender == 'male' %}checked{% endif %}> 남자
        <input type="radio" name="gender" value="female" {% if request.POST.gender == 'female' %}checked{% endif %}> 여자
        <br>
        생년월일: <br>
        <input name="birth_year" type="text" placeholder="YYYY" maxlength="4" value="{{ request.POST.birth_year }}">년
        <input name="birth_month" type="text" placeholder="MM" maxlength="2" value="{{ request.POST.birth_month }}">월
        <input name="birth_day" type="text" placeholder="DD" maxlength="2" value="{{ request.POST.birth_day }}">일
        <br>
        <input type="checkbox" name="privacy_agree" {% if request.POST.privacy_agree %}checked{% endif %}> 개인 정보 수집 및 이용(필수)
        <br><br>
        <input type="submit" class="btn btn-primary" value="가입">
        {% if missing_fields %}
            <p style="color: red;">{{ missing_fields.0 }}</p>
        {% endif %}
    </form>
</div>
{% endblock %}

Team1/signInUp/templates/signup_complete.html
<!DOCTYPE html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>회원가입완료</title>
    {% load static %}
    <link rel="stylesheet" href="{% static 'css/signin.css' %}">
</head>
<body>
    <div class="container">
        <img src="{% static 'img/logo.png' %}" alt="CLASSFIT 로고" class="logo">
        <p>환영합니다, <span id="nickname">{{ nickname }}</span>님</p>
        <p>회원가입이 완료되었습니다.</p>
        <a href="{% url 'signInUp:login' %}">
            <button id="loginButton">로그인하러 가기</button>
        </a>
    </div>
</body>
</html>